### ISSUE TITLE
Can NOT build 

### ISSUE THREAD

**Issue by anhldbk** [xinthink/rnmk-demo#12]
Something goes wrong. I can't execute `run-android`. 

Here are the details:

![screenshot from 2016-03-07 09-16-08](https://cloud.githubusercontent.com/assets/3270746/13559298/5c747d00-e445-11e5-8e81-036178969f7b.png)

**Comment by mihado** [comment]
In `android/build.gradle` you'd need to add add `de.undercouch:gradle-download-task:2.0.0` as dependency.
