### ISSUE TITLE
To focus a text box needs two tap

### ISSUE THREAD

**Issue by efkan** [xinthink/rnmk-demo#14]
First of all, thank you for this useful tools and demo app.

I've initialized a new react-native project to run rnmk-demo. 
Then I copied everything to the new project except `Android` folder.
I applied the instructions for Android of `react-native-material-kit` library.

Now, I can run the demo app on the Android emulator. 

However to enter a textfield in the demo, I have to tap two times. But I should enter the textfield to text something by tapping just one time.

What's wrong with my demo app?

**Comment by VectorM** [comment]
Some problem with Floating Label.
Very hard to click on input
