### ISSUE TITLE
ld: library not found for -lRCTMaterialKit

### ISSUE THREAD

**Issue by idibidiart** [xinthink/rnmk-demo#2]
I ran these commands:
1. npm link ../react-native-material-kit
2. npm install
3. npm start (error: couldn't find packager.sh)

Ran the XCode project for rnmk-demo and had the following error:
ld: library not found for -lRCTMaterialKit

Product-->Scheme is set to Example

XCode 7.1, OS X Yosemite

**Comment by Crash--** [comment]
Open rnmk project -> right click on Librairies -> Add files to RNMKDemo -> Select RCTMaterialKit.xcodeproj

This should fix your issue.

**Comment by xinthink** [comment]
Thanks @Crash-- 
@idibidiart is the problem fixed?

**Comment by idibidiart** [comment]
@xinthink 

No, the build succeeds after adding RCTMaterialKit.xcodeproj to RNMKDemo project under Libraries

But then the packager fails to start because of the lack of proper path to packager which should be `node_modules/react-native/packager/packager.sh` ... After adding the path to the RN packager in package.json the packager itself starts up but when the app requests files the packager throws the following errors and causes the app to fail ( i had done `npm link ../react-native-material-kit` already)

```React packager ready.

[7:51:54 AM] <END>   Crawling File System (4212ms)
[7:51:54 AM] <START> Building in-memory fs for JavaScript
[7:51:55 AM] <END>   Building in-memory fs for JavaScript (602ms)
[7:51:55 AM] <START> Building in-memory fs for Assets
[7:51:55 AM] <END>   Building in-memory fs for Assets (539ms)
[7:51:55 AM] <START> Building Haste Map
[7:51:56 AM] <START> Building (deprecated) Asset Map
[7:51:56 AM] <END>   Building (deprecated) Asset Map (154ms)
[7:51:56 AM] <END>   Building Haste Map (818ms)
[7:51:56 AM] <END>   Building Dependency Graph (6178ms)
[7:51:58 AM] <START> request:/index.ios.bundle?platform=ios
[7:51:58 AM] <START> find dependencies
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/buttons.js
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/styles.js
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/textfields.js
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/toggles.js
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/progress.js
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/sliders.js
Unable to resolve module react-native-material-kit from /Users/.../rnmk-demo/app/cards.js```

Update:

I did 'npm link ../react-native-material-kit`then`rm -rf node_modules`both in rnmk-demo then`npm install`and`npm start` and now it seems to work but some of the components are not fully functioning. For example, clicking on the buttons in simulator does nothing and trying to select the second radio button can't be selected (as intended?). Clicking anywhere on the cards section does nothing (as intended?) and clicking on the slider range moves the slider once but I can't seem to be able to move it again. Does that sound like I got something wrong in my setup, or you're still working on the components :) ?

**Comment by xinthink** [comment]
RN's packager cannot resolve symbolic links (results of `npm link`) facebook/react-native#637, that's why the RNMK module is missing

So you have to use the `./packager.sh` under the root of rnmk-demo, which is supposed to be called by `npm start`, the failure is fixed in the PR #3 , calling `./packager.sh` should also work

**Comment by idibidiart** [comment]
yeah that fixes the packager issue

but under Libraries when starting from a fresh repo, RCTMaterialKit.xcodeproj shows up in red color. So I  have to delete it then Add Files to RNMKDemo and select RCTMaterialKit.xcodeproj from the react-native-material-kit project in order for it to be added. Anyway you can amend the getting started instructions?  @xinthink :)

**Comment by xinthink** [comment]
Sure
