### ISSUE TITLE
Checkbox is missing

### ISSUE THREAD

**Issue by jjchula** [xinthink/rnmk-demo#5]
Thanks for providing the demo.
All work except toggles. 
This demo uses react-native-material-kit  v0.2.4. The file app/toggles.js looks for MKCheckbox but no Checkbox.js in the lib/mdl. Or I miss something.

**Comment by jjchula** [comment]
The problem is Checkbox.js is not in npm.

**Comment by xinthink** [comment]
You're right, Checkbox is in the master branch for now.
I'd like to fix some bug before publishing to npm.
